### ISSUE TITLE
Trying to get rid of stateful components

### ISSUE THREAD

**Issue by TCMiranda** [gilbox/elegant-react#2]
Hi, I'm trying to get some help here..

I read an introduction about "elegant-react" at Medium, and the approach to the renderer function, which holds the state, was realy good.

So I started on a new project which i had the chance to use it, but in practice, not all my components could be stateless, using the sub edit function, mainly because some were dynamic.

What i did, was wrapping all of then in a object wrapper, like

```
editComponents = sub( edit, 'components' )
```

And then, at my component

```
editComponent = sub( editComponent, index ) // some index like 1,2...
```

I thought i might be doing something wrong here, cause it loses the concept of editing some part like "phone" and then, to "editPhone"..

It was even worst when i did

```
<Draggable render={ () => <HeaderLayout data={ data }/> } >
    Header
</Draggable>
```

It is a draggable component which renders <HeaderLayout /> when dropped in the right place.

So, what I am trying to explain here, are my problems developing when following your scheme.

You might could help me find a better way of doing it, or even might come with some solutions to that problem.

I know that sometimes those kind of "frameworks" are good for simple apps, reather then complex ones, but i realy want to find a way of using it to a complex situation like this.

Thanks!
Regards

**Comment by TCMiranda** [comment]
I would appreciate if you could point me some material about using only one stateful component.

Wouldn't it be good to have some well defined @stateful components which are the ones that holds some own edit() function?

What i am saying is, seems that at some point, you could have to create sub "Renderer" component. Would it be good to explicitly say so?

**Comment by gilbox** [comment]
Interesting question @TCMiranda, here are some thoughts...

> I know that sometimes those kind of "frameworks" are good for simple apps, reather then complex ones, but i realy want to find a way of using it to a complex situation like this.

I agree with this statement in general, although elegant-react really is not a framework. All it offers is a decorator that optimizes shouldComponentUpdate to work with immutable data and a subedit function, the rest is up to you. The only somewhat complex project using the approach outline in my medium article is [browser.html](https://github.com/mozilla/browser.html), so it's certainly not an extensively battle-tested architecture if that's what you're looking for.

> Wouldn't it be good to have some well defined @stateful components which are the ones that holds some own edit() function?

I'm not sure what `@stateful` would look like, but there's currently nothing stopping you from using stateful components with elegant-react. In fact, the [elegant-react-hot-demo](https://github.com/gilbox/elegant-react-hot-demo) uses stateful components by virtue of relying on [react-motion](https://github.com/chenglou/react-motion) (a stateful component) for animation. (Note also in elegant-react-hot-demo I do away with the `Renderer` component in favor of `Atom`, although the concept is similar)

> What i am saying is, seems that at some point, you could have to create sub "Renderer" component. Would it be good to explicitly say so?

I really need to see more of your code to understand your use case, but yes something like this might make sense where a sub-component is using `setState` to directly "select" a portion of the global app state instead of passing down props from the root component. That's more or less how [redux](https://github.com/gaearon/redux) works, afaik.

**Comment by gilbox** [comment]
btw, I was following you until you said:

> I thought i might be doing something wrong here, cause it loses the concept of editing some part like "phone" and then, to "editPhone"..

I don't understand this part of the question. Also, I don't understand what you're doing with `Draggable`

**Comment by TCMiranda** [comment]
Thank you @gilbox!

Let me try to better explain my goals and the problems I faced.

First, I was searching for easier, smaller, less complex and more intuitive ways of defining a new components. Also working better with SCU

So i found your "helpers" (lets call it helpers..) and I liked the way you could do everything inside the render, actually, I liked the component as a function also.

Example

``` Javascript
class PhoneInput extends Component {
  render() {

    const { value, editPhone } = this.props;

    return (
      <input value={formatPhone(value)}
             onChange={ event =>
                 editPhone( phone => parsePhone(event.target.value) ) } />
    )
  }
}
```

That is what I was mentioning before, the PhoneInput gets `{ value, editPhone }` from props, renders the value and "edit the phone" on change. See? But I can't acchieve this kind of "literal value" without using more stateful components.

I am building a Drag n Drop app, which the `<Draggable />` are dropped onto the `<DropTarget />`.

When it drops, the `<DropTarget />` recieves the props of the `<Draggable />`, which contains the component that should be rendered inside the `<DropTarget />`.

Exemple

``` Javascript
{/* The draggable component, which render a <HeaderLayout /> at drop */}
{/* Data recieved from props, but i cant pass sub( edit, 'HeaderLayout') */}
{/*   because there may be more than one <HeaderLayout at the same time /> */}
<Draggable render={ () => <HeaderLayout data={ data } /> }>
    Header
</Draggable>

```

Example `<HeaderLayout />`

``` Javascript
class HeaderLayout extends Component {
    render() {

        const { title, subtitle } = this.props;

        return (
            <div style={ /*...*/ }>
                <h1>{ title }<h1>
                <span>{ subtitle }</span>
            </div>
        );
    }
}
```

It fits the schema, but i cant easily create a `sub( edit, '' )` function for each `<HeaderLayout />` rendered.

That could be a component which holds it own state, or I would have to hack around the subedit, which is not intuitive.

Also, I have more than one `<DropTarget />`, so i had to use their index to create a sub( edit, index ) function.

``` Javascript
const initialState = fromJS({
    dropTargets: [ rawTarget, rawTarget, rawTarget ]
});

/* Inside render() */

const { data, editTargets } = this.props;
const targets = data.get('dropTargets');

/*...*/

{ targets.toJS().map(( /*...*/ target, index) => (
    <DropTarget editDropTarget={ sub(editTargets, index) }
                key={ index } />
))}
```

It is not as good as the PhoneInput example, see: My app holds a component that renders Draggables and DropTargets. There are two or more DropTargets, each holding a edit function which apply value to their own index of DropTargets. Each dropTarget state, holds one Layout, which is rendered by the Draggable component, at n DropTargets. Each Layout is also editable, so their states are important. I need to make it be easily accessed by my global state.

That way, my global state is, for example

``` Javascript
({
    data: {
        /* General State of my app */
        menu: false,
        user: {},
        contact: {},
        /* And then my DragnDrop state logic */
        dropTargets: {
            0: { elem: 'HeaderLayout' /*...*/ },
            1: { elem: 'HeaderLayout' /*...*/ },
            2: { elem: 'HeaderLayout' /*...*/ },
        },
        /* The data of the Layouts can't be stored like: */
        headerLayoutData: { title: 'Header', subtitle: 'Layout' },
        /* Because there may be a second Layout of the same type */
        headerLayoutData2: { title: 'Header', subtitle: 'Layout' },
        /* Should I */
        headerLayoutData: [
            /* index of drop target */
            0: { title: 'Header', subtitle: 'Layout' }
        ]
    }
})
```

I don't feel that it is right to store dropTargets inside that global state. Although it is possible. And the headerLayoutData is definitely too complex.

So, maybe I should have more than one stateful component, and define them with some kind of mechanism (dont know how), so it could be easily accessed (or give access).

Ok... Some thoughts about it?

But in general, liked very much to try this approach, and I think that this is the path to develop a easy way of working with React components.

Thaks!

**Comment by TCMiranda** [comment]
Oh, also, the `@stateful` I mentioned, was some easy way to define this:

``` Javascript
// the Renderer component manages the top-level app state
class Renderer extends Component {
  constructor() {
    super(...arguments);
    this.state = {data:this.props.initialState};
  }
  edit (transform) {
    this.setState({data: transform(this.state.data)})
  }
  render() {
    return <App
      data={this.state.data}
      edit={::this.edit} />
  }
}
```

**Comment by TCMiranda** [comment]
One more thing.. Ok, the package is a about some helpers, but the way you described it, could be approached into a functional framework

**Comment by gilbox** [comment]
TC, I have to admit I am pretty confused now. I am not entirely sure what you are trying to accomplish, or more likely, how you are trying to accomplish it. I think I understand the drag-n-drop behavior you are going for. But many parts are confusing to me. 

So, I think that this thread is not the best way for me to understand what you are doing. I would love it if you could push up a repo with a minimal example of a working or semi-working example of what you are trying to accomplish.

That said I think that maybe you want to gain access to top-level `edit` function from any component? If that is the case, the way to do that is to use React's context to pass down the _global state manager_ throughout the component hierarchy. The alternative is to pass it down explicitly with props but that's pretty tedious.

The [Atom](https://github.com/gilbox/elegant-react-hot-demo/blob/master/src/Atom.js) is the sort of object you can pass with context.

```
class App extends Component {
   static childContextTypes = {
    atom: React.PropTypes.object
   }
   getChildContext() {
    return { atom: this.props.atom }
   }
       /* ... render, etc ... */
}
```

then grab the state whenever you need it...

```
class ComponentThatManagesState extends Component {
    static contextTypes = {
        atom: React.PropTypes.object
    }
    render() {
         const {atom} = this.context;
         const edit = ::atom.updateState;
         const editFoo = sub(edit, 'foo');
         return <button onClick={event => editFoo(value => 'hello')}>
            {atom.get('foo')}
         </button>
    }
}
```

You could probably do the same thing with Renderer by assigning Renderer's `this` instance to context, but that's kind of clunky.

Not sure if this helps at all or if I'm going in the completely wrong direction. Let me know what you think.

**Comment by gilbox** [comment]
If you want multiple components to have atoms, I could image a decorator that manages an atom:

```
@stateful(fromJS({phone: '5555555555'})   // the first arg is the atom's initial state
class StatefulComponent extends Component {
  render() {
    const {state, edit} = this.props;   // state and edit are passed in by @stateful
    return (
      <PhoneInput 
        value={state.get('phone')}
        editPhone={sub(edit, 'phone')} />
    )
  }
}
```

But in many (most?) cases maybe it's a bad idea.

**Comment by TCMiranda** [comment]
@gilbox Thanks for your answer!

I am not sure if that is the answer for me.

Actually, I did created the exactly same decorator as you exemplified, because I really couldn't find a way to dynamically create a context (subedit) for all my components.

I am realizing it is not that easy to understand my problem, and I think it may not be the case for now, but after I finish, I'll try to exemplify it better for you.

The point for me, is that it is important to define the state of all the components dynamically created with the drag and drop mechanism. 
So I am trying to achieve this by creating the whole app based on this premise.

It would be great to store a json which after converted to my initial state, translates to the whole app mounted, but in the other hand, that must be easy so the app could me easily Improved (obviously). 

I am not in my workspace right now, so I am not giving you any code. But after describing it, I think I now how to explain it, and I want to make some small app example for you later.

Thank you

Regards, 
Tiago.

**Comment by TCMiranda** [comment]
Hello again @gilbox 

So, I am giving you some update here...

My code was exactly this:

``` Javascript
<Draggable render={ () => <HeaderLayout data={ data }/> } >
    Header
</Draggable>
```

The problem was actually my design, not the "subedit pattern". 

As you can see, I assigned a handler (the `render={...}` attribute) which renders a new component when dragged to a new location. In another words, I was cloning the component inside `render={...}` each time it was dragged.

I cant find a way of assign a "namespace" to the edit function of each of those components, but as I realised, thats not common, and could have been fixed with a better "factory" for those components.

Did you got it?

Summarizing, now I fixed that issue, and the app is working very well with that pattern in mind. 

Only a top level @stateful component and a lot of other components which are represented by a subtree of the top level one.

Another good thing, is that each of the components receives only part of the tree, which also helps to not trigger shouldComponentUpdate.

I've also created another `sub` function, which accepts `sub(sub(edit, 'a'), 'b')`.

Thats it, thanks for your ideas, really helped me out!

**Comment by gilbox** [comment]
Glad you got it sorted out :+1: 

btw, at some point, I'll probably remove the `sub` function from this project so you'll have to supply your own. It  just makes no sense to have it as part of this lib since there are so many variations of `sub`.
