### ISSUE TITLE
Immutable edits with subsequent mutations

### ISSUE THREAD

**Issue by TCMiranda** [gilbox/elegant-react#3]
I am just referencing an issue that could happen at the edit function:
https://github.com/goatslacker/alt/pull/214

As you can see, react sometimes dalays the execution of `setState()`. When that happens, subsequent calls to `edit()` can transform the same value of `this.state`.

``` Javascript
  edit (transform) {
    /* this.state can not yet have been mutated */
    this.setState({data: transform(this.state.data)})
  }
```

Regards

**Comment by gilbox** [comment]
I'm aware of this but it really has nothing to do with elegant-react since the `setState()` strategy is left up to the user.

**Comment by TCMiranda** [comment]
Great! Closing this... 
Regards
